### ISSUE TITLE
RTL UI rendering issues

### ISSUE THREAD

**Issue by CripyIce** [iliyass-zamouri/flutter_agenda#8]
Hi there,
Just started using this package for my app that supports RTL layout, and encountered some issues.
1. Error when scrolling the UI horizontally and then vertically:
```
======== Exception caught by gesture ===============================================================
The following _CastError was thrown while handling a gesture:
Null check operator used on a null value

When the exception was thrown, this was the stack: 
#0      _FlutterAgendaState._buildMainContent.<anonymous closure>.<anonymous closure> (package:flutter_agenda/src/views/agenda_screen.dart:165:49)
#1      PillarView.build.<anonymous closure> (package:flutter_agenda/src/views/pillar_view.dart:31:45)
#2      TapGestureRecognizer.handleTapDown.<anonymous closure> (package:flutter/src/gestures/tap.dart:581:61)
#3      GestureRecognizer.invokeCallback (package:flutter/src/gestures/recognizer.dart:198:24)
#4      TapGestureRecognizer.handleTapDown (package:flutter/src/gestures/tap.dart:581:11)
#5      BaseTapGestureRecognizer._checkDown (package:flutter/src/gestures/tap.dart:287:5)
#6      BaseTapGestureRecognizer.didExceedDeadline (package:flutter/src/gestures/tap.dart:258:5)
#7      PrimaryPointerGestureRecognizer.didExceedDeadlineWithEvent (package:flutter/src/gestures/recognizer.dart:591:5)
#8      PrimaryPointerGestureRecognizer.addAllowedPointer.<anonymous closure> (package:flutter/src/gestures/recognizer.dart:535:41)
(elided 11 frames from class _RawReceivePortImpl, class _Timer, dart:async, and dart:async-patch)
Handler: "onTapDown"
Recognizer: TapGestureRecognizer#60ba6
  debugOwner: GestureDetector
  state: possible
  button: 1
====================================================================================================

```

2. When reaching the top/bottom limit and trying to scroll the right side tries to scroll with laggy UI, and also you can just scroll the right pane which is strange.
3. The `AgendaEvent` UI is cut out on the right edge of the first `Resource` so text is not fully displayed.
4. The horizontal dividers of the panes doesn't share the same thickness and the same height.

Code I used:
```dart
FlutterAgenda(
      resources: [
        Resource(
          head: Header(title: 'מרסל אוחנה', object: 1, color: Colors.yellow),
          events: [
            AgendaEvent(
              title: 'תור לציפורניים - יוסי שיטרית',
              start: EventTime(hour: 18, minute: 00),
              end: EventTime(hour: 19, minute: 00),
            ),
          ],
        ),
        Resource(
          head: Header(title: 'מוגוטה', object: 2, color: Colors.yellow),
          events: [
            AgendaEvent(
              title: 'תור לציפורניים - יוסי שיטרית',
              start: EventTime(hour: 18, minute: 00),
              end: EventTime(hour: 19, minute: 00),
            ),
          ],
        ),
      ],
      agendaStyle: AgendaStyle(
        startHour: 9,
        endHour: 24,
        headerLogo: HeaderLogo.bar,
        timeItemWidth: 45,
        timeSlot: TimeSlot.full,
        decorationLineBorderColor: Colors.transparent,
      ),
    )
```

![Simulator Screen Shot - iPhone 13 Pro - 2022-04-20 at 15 36 16](https://user-images.githubusercontent.com/26387823/164232185-aec4d494-c836-4894-b70a-47ddd69c9bbb.png)

https://user-images.githubusercontent.com/26387823/164233522-5481e711-b531-4d76-89bd-8fb43c8a2f9d.mp4

**Comment by iliyass-zamouri** [comment]
Hi  @CripyIce, I juste debuged the code you provided, 

```
Handler: "onTapDown"
Recognizer: TapGestureRecognizer#60ba6
  debugOwner: GestureDetector
  state: possible
  button: 1
```
to fix this bug you should provide an onTap to the 
```
AgendaEvent(
      title: 'תור לציפורניים - יוסי שיטרית',
      start: EventTime(hour: 18, minute: 00),
      end: EventTime(hour: 19, minute: 00),
      onTap: () => print('do something'),
),
```

**Comment by iliyass-zamouri** [comment]
About the **RTL Support** is now currently under development.

**Comment by iliyass-zamouri** [comment]
I added the Support for Directionality its under version 3.1.0, update your version to the latest and add the **direction** field to your AgendaStyle property.
```dart
agendaStyle: AgendaStyle(
    direction: TextDirection.ltr,
    startHour: 9,
    endHour: 24,
    headerLogo: HeaderLogo.bar,
    timeItemWidth: 45,
    timeSlot: TimeSlot.full,
    decorationLineBorderColor: Colors.transparent,
),
```

**Comment by iliyass-zamouri** [comment]
@CripyIce, Don't forget to provide an onTap function:
```dart
FlutterAgenda(
  resources: resources,
  agendaStyle: AgendaStyle(
    startHour: 9,
    endHour: 20,
    direction: TextDirection.ltr,
    headerLogo: HeaderLogo.bar,
    timeItemWidth: 45,
    timeSlot: TimeSlot.quarter,
  ),
  onTap: (EventTime clickedTime,dynamic object) {
    print("Clicked time: ${clickedTime.hour}:${clickedTime.minute}");
    // dont forget to cast the object back to it's original type
    print("Head Object related to the resource: $object");
  },
)
```

**Comment by CripyIce** [comment]
@iliyass-zamouri Looks better now.
But still weird scrolling issues.

**Comment by iliyass-zamouri** [comment]
Which flutter sdk version your are using?

**Comment by CripyIce** [comment]
Flutter 2.10.5.
